name: docs-test-3
 
on:
  push:
    branches:
      - master
      - develop
  release:
    types:
      [published]
  workflow_dispatch:
 
jobs:
 
  build_docs_job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: bash ./scripts/setup_gh.sh
    - name: Test with tox
      run: tox -vv -e docs
    - name: Deploy doc on gh-pages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: bash docs/deploy.sh
